// Autogenerated AST node
package org.python.antlr.ast;
import org.antlr.v4.runtime.CommonToken;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.python.antlr.AST;
import org.python.antlr.ast.VisitorIF;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.excepthandler;
import org.python.antlr.base.expr;
import org.python.antlr.base.mod;
import org.python.antlr.base.slice;
import org.python.antlr.base.stmt;
import org.python.core.ArgParser;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyUnicode;
import org.python.core.PyStringMap;
import org.python.core.PyLong;
import org.python.core.PyType;
import org.python.core.PyList;
import org.python.core.PyNewWrapper;
import org.python.core.Visitproc;
import org.python.annotations.ExposedGet;
import org.python.annotations.ExposedMethod;
import org.python.annotations.ExposedNew;
import org.python.annotations.ExposedSet;
import org.python.annotations.ExposedType;
import org.python.annotations.ExposedSlot;
import org.python.annotations.SlotFunc;
import java.util.Objects;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;

@ExposedType(name = "_ast.SetComp", base = expr.class)
public class SetComp extends expr {
public static final PyType TYPE = PyType.fromClass(SetComp.class);
    private expr elt;
    public expr getInternalElt() {
        return elt;
    }
    public void setInternalElt(expr elt) {
        this.elt = elt;
    }
    @ExposedGet(name = "elt")
    public PyObject getElt() {
        return elt;
    }
    @ExposedSet(name = "elt")
    public void setElt(PyObject elt) {
        this.elt = AstAdapters.py2expr(elt);
    }

    private java.util.List<comprehension> generators;
    public java.util.List<comprehension> getInternalGenerators() {
        return generators;
    }
    public void setInternalGenerators(java.util.List<comprehension> generators) {
        this.generators = generators;
    }
    @ExposedGet(name = "generators")
    public PyObject getGenerators() {
        return new PyList(generators);
    }
    @ExposedSet(name = "generators")
    public void setGenerators(PyObject generators) {
        this.generators = AstAdapters.py2comprehensionList(generators);
    }


    private final static PyUnicode[] fields =
    new PyUnicode[] {new PyUnicode("elt"), new PyUnicode("generators")};
    @ExposedGet(name = "_fields")
    public PyUnicode[] get_fields() { return fields; }

    private final static PyUnicode[] attributes =
    new PyUnicode[] {new PyUnicode("lineno"), new PyUnicode("col_offset")};
    @ExposedGet(name = "_attributes")
    public PyUnicode[] get_attributes() { return attributes; }

    public SetComp() {
        super(TYPE);
    }
    @ExposedNew
    @ExposedSlot(SlotFunc.NEW)
    public static PyObject SetComp_new(PyNewWrapper _new, boolean init, PyType subtype, PyObject[]
    args, String[] keywords) {
        return new SetComp(subtype);
    }
    @ExposedMethod(names={"__init__"})
    public void SetComp___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("SetComp", args, keywords, new String[]
            {"elt", "generators", "lineno", "col_offset"}, 2, true);
        setElt(ap.getPyObject(0, Py.None));
        setGenerators(ap.getPyObject(1, Py.None));
        PyObject lin = ap.getOptionalArg(2);
        if (lin != null) {
            lineno = lin;
        }

        PyObject col = ap.getOptionalArg(3);
        if (col != null) {
            col_offset = col;
        }

    }

    public SetComp(PyObject elt, PyObject generators) {
        super(TYPE);
        setElt(elt);
        setGenerators(generators);
    }

    // called from derived class
    public SetComp(PyType subtype) {
        super(subtype);
    }

    public SetComp(Token token, expr elt, java.util.List<comprehension> generators) {
        super(TYPE, token);
        this.elt = elt;
        if (this.elt != null)
            this.elt.setParent(this);
        this.generators = generators;
        if (generators == null) {
            this.generators = new ArrayList<>(0);
        }
        for(int i = 0; i < this.generators.size(); i++) {
            PythonTree t = this.generators.get(i);
            if (t != null)
                t.setParent(this);
        }
    }

    public SetComp(PythonTree tree, expr elt, java.util.List<comprehension> generators) {
        super(TYPE, tree);
        this.elt = elt;
        if (this.elt != null)
            this.elt.setParent(this);
        this.generators = generators;
        if (generators == null) {
            this.generators = new ArrayList<>(0);
        }
        for(int i = 0; i < this.generators.size(); i++) {
            PythonTree t = this.generators.get(i);
            if (t != null)
                t.setParent(this);
        }
    }

    public SetComp copy() {
        return new SetComp(this.getToken(), this.elt, this.generators);
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "SetComp";
    }

    @Override
    public String toStringTree() {
        StringBuffer sb = new StringBuffer("SetComp(");
        sb.append("elt=");
        sb.append(dumpThis(elt));
        sb.append(",");
        sb.append("generators=");
        sb.append(dumpThis(generators));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> boolean enter(VisitorIF<R> visitor) {
        return visitor.enterSetComp(this);
    }

    public <R> void leave(VisitorIF<R> visitor) {
        visitor.leaveSetComp(this);
    }

    public <R> R accept(VisitorIF<R> visitor) {
        return visitor.visitSetComp(this);
    }

    public <R> void traverse(VisitorIF<R> visitor) {
        if (elt != null)
            elt.accept(visitor);
        if (generators != null) {
            for (PythonTree t : generators) {
                if (t != null)
                    t.accept(visitor);
            }
        }
    }

    public void replaceField(expr value, expr newValue) {
        if (value == elt) this.elt = newValue;
    }

    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

    @ExposedGet(name = "lineno")
    public int getLineno() {
        return super.getLineno();
    }

    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = new PyLong(num);
    }

    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        return super.getCol_offset();
    }

    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = new PyLong(num);
    }

}
