// Autogenerated AST node
package org.python.antlr.ast;
import org.antlr.v4.runtime.CommonToken;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.python.antlr.AST;
import org.python.antlr.ast.VisitorIF;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.excepthandler;
import org.python.antlr.base.expr;
import org.python.antlr.base.mod;
import org.python.antlr.base.slice;
import org.python.antlr.base.stmt;
import org.python.core.ArgParser;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyUnicode;
import org.python.core.PyTuple;
import org.python.core.PyStringMap;
import org.python.core.PyLong;
import org.python.core.PyType;
import org.python.core.PyList;
import org.python.core.PyNewWrapper;
import org.python.core.Visitproc;
import org.python.annotations.ExposedGet;
import org.python.annotations.ExposedMethod;
import org.python.annotations.ExposedNew;
import org.python.annotations.ExposedSet;
import org.python.annotations.ExposedType;
import org.python.annotations.ExposedSlot;
import org.python.annotations.SlotFunc;
import java.util.Objects;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;

@ExposedType(name = "_ast.withitem", base = AST.class)
public class withitem extends PythonTree {
    public static final PyType TYPE = PyType.fromClass(withitem.class);
    private expr context_expr;
    public expr getInternalContext_expr() {
        return context_expr;
    }
    public void setInternalContext_expr(expr context_expr) {
        this.context_expr = context_expr;
    }
    @ExposedGet(name = "context_expr")
    public PyObject getContext_expr() {
        return context_expr;
    }
    @ExposedSet(name = "context_expr")
    public void setContext_expr(PyObject context_expr) {
        this.context_expr = AstAdapters.py2expr(context_expr);
    }

    private expr optional_vars;
    public expr getInternalOptional_vars() {
        return optional_vars;
    }
    public void setInternalOptional_vars(expr optional_vars) {
        this.optional_vars = optional_vars;
    }
    @ExposedGet(name = "optional_vars")
    public PyObject getOptional_vars() {
        return optional_vars;
    }
    @ExposedSet(name = "optional_vars")
    public void setOptional_vars(PyObject optional_vars) {
        this.optional_vars = AstAdapters.py2expr(optional_vars);
    }


    private final static PyUnicode[] fields =
    new PyUnicode[] {new PyUnicode("context_expr"), new PyUnicode("optional_vars")};
    @ExposedGet(name = "_fields")
    public PyObject get_fields() { return new PyTuple(fields); }

    private final static PyUnicode[] attributes = new PyUnicode[0];
    @ExposedGet(name = "_attributes")
    public PyObject get_attributes() { return Py.EmptyTuple; }

    public withitem() {
        super(TYPE);
    }
    @ExposedNew
    @ExposedSlot(SlotFunc.NEW)
    public static PyObject withitem_new(PyNewWrapper _new, boolean init, PyType subtype, PyObject[]
    args, String[] keywords) {
        return new withitem(subtype);
    }
    @ExposedMethod(names={"__init__"})
    public void withitem___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("withitem", args, keywords, new String[]
            {"context_expr", "optional_vars"}, 2, true);
        setContext_expr(ap.getPyObject(0, Py.None));
        setOptional_vars(ap.getPyObject(1, Py.None));
    }

    public withitem(PyObject context_expr, PyObject optional_vars) {
        super(TYPE);
        setContext_expr(context_expr);
        setOptional_vars(optional_vars);
    }

    // called from derived class
    public withitem(PyType subtype) {
        super(subtype);
    }

    public withitem(Token token, expr context_expr, expr optional_vars) {
        super(TYPE, token);
        this.context_expr = context_expr;
        if (this.context_expr != null)
            this.context_expr.setParent(this);
        this.optional_vars = optional_vars;
        if (this.optional_vars != null)
            this.optional_vars.setParent(this);
    }

    public withitem(PythonTree tree, expr context_expr, expr optional_vars) {
        super(TYPE, tree);
        this.context_expr = context_expr;
        if (this.context_expr != null)
            this.context_expr.setParent(this);
        this.optional_vars = optional_vars;
        if (this.optional_vars != null)
            this.optional_vars.setParent(this);
    }

    public withitem copy() {
        return new withitem(this.getToken(), this.context_expr, this.optional_vars);
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "withitem";
    }

    @Override
    public String toStringTree() {
        StringBuffer sb = new StringBuffer("withitem(");
        sb.append("context_expr=");
        sb.append(dumpThis(context_expr));
        sb.append(",");
        sb.append("optional_vars=");
        sb.append(dumpThis(optional_vars));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> boolean enter(VisitorIF<R> visitor) {
        return false;
    }

    public <R> void leave(VisitorIF<R> visitor) {
    }

    public <R> R accept(VisitorIF<R> visitor) {
        traverse(visitor);
        return null;
    }

    public <R> void traverse(VisitorIF<R> visitor) {
        if (context_expr != null)
            context_expr.accept(visitor);
        if (optional_vars != null)
            optional_vars.accept(visitor);
    }

    public void replaceField(expr value, expr newValue) {
        if (value == context_expr) this.context_expr = newValue;
        if (value == optional_vars) this.optional_vars = newValue;
    }

    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

}
