// Autogenerated AST node
package org.python.antlr.ast;
import org.antlr.v4.runtime.Token;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.expr;
import org.python.antlr.base.stmt;
import org.python.core.ArgParser;
import org.python.core.AstList;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyUnicode;
import org.python.core.PyStringMap;
import org.python.core.PyType;
import org.python.annotations.ExposedGet;
import org.python.annotations.ExposedMethod;
import org.python.annotations.ExposedNew;
import org.python.annotations.ExposedSet;
import org.python.annotations.ExposedType;

import java.util.ArrayList;

@ExposedType(name = "_ast.Assign", base = stmt.class)
public class Assign extends stmt {
public static final PyType TYPE = PyType.fromClass(Assign.class);
    private java.util.List<expr> targets;
    public java.util.List<expr> getInternalTargets() {
        return targets;
    }
    public void setInternalTargets(java.util.List<expr> targets) {
        this.targets = targets;
    }
    @ExposedGet(name = "targets")
    public PyObject getTargets() {
        return new AstList(targets, AstAdapters.exprAdapter);
    }
    @ExposedSet(name = "targets")
    public void setTargets(PyObject targets) {
        this.targets = AstAdapters.py2exprList(targets);
    }

    private expr value;
    public expr getInternalValue() {
        return value;
    }
    public void setInternalValue(expr value) {
        this.value = value;
    }
    @ExposedGet(name = "value")
    public PyObject getValue() {
        return value;
    }
    @ExposedSet(name = "value")
    public void setValue(PyObject value) {
        this.value = AstAdapters.py2expr(value);
    }


    private final static PyUnicode[] fields =
    new PyUnicode[] {new PyUnicode("targets"), new PyUnicode("value")};
    @ExposedGet(name = "_fields")
    public PyUnicode[] get_fields() { return fields; }

    private final static PyUnicode[] attributes =
    new PyUnicode[] {new PyUnicode("lineno"), new PyUnicode("col_offset")};
    @ExposedGet(name = "_attributes")
    public PyUnicode[] get_attributes() { return attributes; }

    public Assign() {
        super(TYPE);
    }
    @ExposedNew
    @ExposedMethod
    public void Assign___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("Assign", args, keywords, new String[]
            {"targets", "value", "lineno", "col_offset"}, 2, true);
        setTargets(ap.getPyObject(0, Py.None));
        setValue(ap.getPyObject(1, Py.None));
        int lin = ap.getInt(2, -1);
        if (lin != -1) {
            setLineno(lin);
        }

        int col = ap.getInt(3, -1);
        if (col != -1) {
            setLineno(col);
        }

    }

    public Assign(PyObject targets, PyObject value) {
        super(TYPE);
        setTargets(targets);
        setValue(value);
    }

    // called from derived class
    public Assign(PyType subtype) {
        super(subtype);
    }

    public Assign(Token token, java.util.List<expr> targets, expr value) {
        super(TYPE, token);
        this.targets = targets;
        if (targets == null) {
            this.targets = new ArrayList<>(0);
        }
        for(int i = 0; i < this.targets.size(); i++) {
            PythonTree t = this.targets.get(i);
            if (t != null)
                t.setParent(this);
        }
        this.value = value;
        if (this.value != null)
            this.value.setParent(this);
    }

    public Assign(PythonTree tree, java.util.List<expr> targets, expr value) {
        super(TYPE, tree);
        this.targets = targets;
        if (targets == null) {
            this.targets = new ArrayList<>(0);
        }
        for(int i = 0; i < this.targets.size(); i++) {
            PythonTree t = this.targets.get(i);
            if (t != null)
                t.setParent(this);
        }
        this.value = value;
        if (this.value != null)
            this.value.setParent(this);
    }

    public Assign copy() {
        return new Assign(this.getToken(), this.targets, this.value);
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "Assign";
    }

    @Override
    public String toStringTree() {
        StringBuffer sb = new StringBuffer("Assign(");
        sb.append("targets=");
        sb.append(dumpThis(targets));
        sb.append(",");
        sb.append("value=");
        sb.append(dumpThis(value));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitAssign(this);
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
        if (targets != null) {
            for (PythonTree t : targets) {
                if (t != null)
                    t.accept(visitor);
            }
        }
        if (value != null)
            value.accept(visitor);
    }

    public void replaceField(expr value, expr newValue) {
        for (int i=0;i<this.targets.size();i++){
            expr thisVal = this.targets.get(i);
            if (value == thisVal) this.targets.set(i,newValue);
        }
        if (value == value) this.value = newValue;
    }

    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

    private int lineno = -1;
    @ExposedGet(name = "lineno")
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = num;
    }

}
