// Autogenerated AST node
package org.python.antlr.ast;
import org.antlr.v4.runtime.CommonToken;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.python.antlr.AST;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.excepthandler;
import org.python.antlr.base.expr;
import org.python.antlr.base.mod;
import org.python.antlr.base.slice;
import org.python.antlr.base.stmt;
import org.python.core.ArgParser;
import org.python.core.AstList;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyUnicode;
import org.python.core.PyStringMap;
import org.python.core.PyType;
import org.python.core.Visitproc;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;

@ExposedType(name = "_ast.Block", base = stmt.class)
public class Block extends stmt {
public static final PyType TYPE = PyType.fromClass(Block.class);
    private java.util.List<stmt> statements;
    public java.util.List<stmt> getInternalStatements() {
        return statements;
    }
    public void setInternalStatements(java.util.List<stmt> statements) {
        this.statements = statements;
    }
    @ExposedGet(name = "statements")
    public PyObject getStatements() {
        return new AstList(statements, AstAdapters.stmtAdapter);
    }
    @ExposedSet(name = "statements")
    public void setStatements(PyObject statements) {
        this.statements = AstAdapters.py2stmtList(statements);
    }


    private final static PyUnicode[] fields =
    new PyUnicode[] {new PyUnicode("statements")};
    @ExposedGet(name = "_fields")
    public PyUnicode[] get_fields() { return fields; }

    private final static PyUnicode[] attributes =
    new PyUnicode[] {new PyUnicode("lineno"), new PyUnicode("col_offset")};
    @ExposedGet(name = "_attributes")
    public PyUnicode[] get_attributes() { return attributes; }

    public Block() {
        super(TYPE);
    }
    @ExposedNew
    @ExposedMethod
    public void Block___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("Block", args, keywords, new String[]
            {"statements", "lineno", "col_offset"}, 1, true);
        setStatements(ap.getPyObject(0, Py.None));
        int lin = ap.getInt(1, -1);
        if (lin != -1) {
            setLineno(lin);
        }

        int col = ap.getInt(2, -1);
        if (col != -1) {
            setLineno(col);
        }

    }

    public Block(PyObject statements) {
        super(TYPE);
        setStatements(statements);
    }

    // called from derived class
    public Block(PyType subtype) {
        super(subtype);
    }

    public Block(Token token, java.util.List<stmt> statements) {
        super(TYPE, token);
        this.statements = statements;
        if (statements == null) {
            this.statements = new ArrayList<>(0);
        }
        for(PythonTree t : this.statements) {
            addChild(t, this.statements);
        }
    }

    public Block(PythonTree tree, java.util.List<stmt> statements) {
        super(TYPE, tree);
        this.statements = statements;
        if (statements == null) {
            this.statements = new ArrayList<>(0);
        }
        for(PythonTree t : this.statements) {
            addChild(t, this.statements);
        }
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "Block";
    }

    @Override
    public String toStringTree() {
        StringBuffer sb = new StringBuffer("Block(");
        sb.append("statements=");
        sb.append(dumpThis(statements));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitBlock(this);
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
        if (statements != null) {
            for (PythonTree t : statements) {
                if (t != null)
                    t.accept(visitor);
            }
        }
    }

    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

    private int lineno = -1;
    @ExposedGet(name = "lineno")
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = num;
    }

}
